//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westwind.Globalization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Westwind.Globalization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save resource: Invalid culture id passed: {0}.
        /// </summary>
        internal static string Can_t_save_resource__Invalid_culture_id_passed {
            get {
                return ResourceManager.GetString("Can_t_save_resource__Invalid_culture_id_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id and Client Secret must be provided..
        /// </summary>
        internal static string Client_Id_and_Client_Secret_must_be_provided {
            get {
                return ResourceManager.GetString("Client_Id_and_Client_Secret_must_be_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id and Client Secret must be provided..
        /// </summary>
        internal static string Client_Id_and_Client_Secret_must_be_provided_ {
            get {
                return ResourceManager.GetString("Client_Id_and_Client_Secret_must_be_provided_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: .
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string for resources is not configured.
        /// </summary>
        internal static string ConnectionStringForResourcesIsNotConfigure {
            get {
                return ResourceManager.GetString("ConnectionStringForResourcesIsNotConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page Resources.
        /// </summary>
        internal static string EditPageResources {
            get {
                return ResourceManager.GetString("EditPageResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension for file resource..
        /// </summary>
        internal static string InvalidFileExtensionForFileResource {
            get {
                return ResourceManager.GetString("InvalidFileExtensionForFileResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search result..
        /// </summary>
        internal static string InvalidSearchResult {
            get {
                return ResourceManager.GetString("InvalidSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Options.
        /// </summary>
        internal static string LocalizationOptions {
            get {
                return ResourceManager.GetString("LocalizationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Table exists already.
        /// </summary>
        internal static string LocalizationTable_Localization_Table_exists_already {
            get {
                return ResourceManager.GetString("LocalizationTable_Localization_Table_exists_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching Recordset found..
        /// </summary>
        internal static string No_matching_Recordset_found {
            get {
                return ResourceManager.GetString("No_matching_Recordset_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ResourceId specified. Can&apos;t add resource.
        /// </summary>
        internal static string NoResourceIdSpecifiedCantAddResource {
            get {
                return ResourceManager.GetString("NoResourceIdSpecifiedCantAddResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file upload data.
        /// </summary>
        internal static string ResourceItemMissingFileUploadData {
            get {
                return ResourceManager.GetString("ResourceItemMissingFileUploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Localization Icons.
        /// </summary>
        internal static string ShowLocalizationIcons {
            get {
                return ResourceManager.GetString("ShowLocalizationIcons", resourceCulture);
            }
        }
    }
}
